networks:
  internal_network:
    driver: overlay

services:
  web:
    image: ghcr.io/minhnguyennhatdev/vltk-market-client:latest
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:3000}
      NODE_ENV: production
    ports:
      - "3000"
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    networks:
      - internal_network
