networks:
  internal_network:
    driver: overlay

services:
  web:
    image: ghcr.io/minhnguyennhatdev/vltk-market-client:latest
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:3000}
      NODE_ENV: production
    restart: unless-stopped
    networks:
      - internal_network
